# Base service'ler — overlay'de değişmez
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  type: ClusterIP
  selector:
    app: order-svc
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  type: ClusterIP
  selector:
    app: payment-svc
  ports:
    - name: http
      port: 8002
      targetPort: 8002
